---
- name: Execute Enterprise Cluster Provisioning Sequence
  hosts: masters
  become: true
  gather_facts: true

  roles:
    - k8s_prepare
  tags:
    - prepare

- name: Run Orchestrated High-Availability Control Plane Bootstrapping
  hosts: masters
  become: true
  gather_facts: true

  roles:
    - k8s_init
  tags:
    - init

- name: Emergency SSH Public Key Injection Pipeline
  hosts: masters
  gather_facts: false # ⚡ Speed up execution by bypassing system fact collection
  become: yes

  tasks:
    - name: Inject keys straight out of group variables
      ansible.builtin.authorized_key:
        user: ubuntu
        state: present
        key: "{{ item }}"
      loop: "{{ authorized_cluster_keys }}"
  tags:
    - pubkeys
